### ISSUE TITLE
Normalize INPUT FILE PATHS / Test if Quotes and Missing/Extra Slashes Work

### ISSUE THREAD

**Issue by gsteve3** [trxn8r/trxn8r#1]
Normalize INPUT FILE PATHS / Test if Quotes and Missing/Extra Slashes Work

- [x] Strip Quotes from value in case someone pastes from Explorer and has douquotes
...or will it handle that?

- [x] TODO: Test quotes! Document results.

<sup>Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>

**Comment by GregSweats** [comment]
Magically it works! Probably since w are just passing the path to the PQ Functions. Sweet.
